package com.example.simplecrud.domain.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

/**
 * Database Table Remarks:
 *   ユーザ
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table public.users
 */
@Data
public class User implements Serializable {
    /**
     * Database Column Remarks:
     *   ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     * Database Column Remarks:
     *   氏名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   パスワード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.pass
     *
     * @mbg.generated
     */
    private String pass;

    /**
     * Database Column Remarks:
     *   メール
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.mail
     *
     * @mbg.generated
     */
    private String mail;

    /**
     * Database Column Remarks:
     *   ステータス
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * Database Column Remarks:
     *   作成日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.created_at
     *
     * @mbg.generated
     */
    private LocalDateTime createdAt;

    /**
     * Database Column Remarks:
     *   更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.changed_at
     *
     * @mbg.generated
     */
    private LocalDateTime changedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.users.comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.users
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}